language: rust
rust: nightly

script:
  - cd additions/rustbook && cargo build --release
  - cp ./target/release/rustbook ./
  - cd ../../ && find . -maxdepth 1 -name '*.md' -exec sed -i 1s/#/%/ {} \;
  - ./additions/rustbook/rustbook build

after_success:
  - bash additions/deploy.sh

branches:
  only: master

env:
  global:
    - secure: "K4uhFAiRnDCG36L4s/RjNh24FWmxW2IrYfyLVzrB8h3GgpULCJ3ji30KK7LFFHCqkgvtBPafu0XEQ422oXdhCeJYtRAl7pgcSeZpUJP15L5nC0BG6Sp9yox0FJDqp44g4eja/TUrcZ3JoAeyxNAWqWdSLMLaakNkJY7WDtLKrJgA03gYVXMWrNReYNSNqnWmHmGTjFFDjJUb+Ul61Sr7Qb+79DtF59J8r/APJbWNLLLXkJx8zgyNJngISJBExUe4Vr9j3zOBgKf5VPOVI4x2YGqKUAGx94xELXmpiAKdoKibo6EE3NIZzD1JI+9IBDgZZEYtKXHe9UPD8ELUaTmz398mcNg0oniC9yU7qwjkGEck+/Zaio9Bs+r1o4ofAL5+7t00XEw1CXxsho4dmoNVpR9wYNwleTn6Jqo4Qqetwc0u1QA2OUizPKfNYIH/d08OLBQayQGIF9WznvNE0AsR/GDhUowpsQppwQRVYDFvw8O3t8kMzKZJxTfIzTMXVb8D2WVQ2uKGmiiWMGSgO1V4kLI18d+KZAlm80R2GSzBHGGeJFZTp6FzarfzzDK2ZyEVsEG6lhcDckdIUWZJESBh24lykO4gnO7UXg1xXTxDpr22Wt6ygoHyc6klMdyjWnXhOeZkmRM1yWCd/Xj2MquF1+FfUXAwhXojbvJYamineEk="
