language: rust
rust: nightly

env:
  global:
    - secure: "VYGOokUvoh/2oDnWUzJvq+qw5/nYa8b2AVl6smBsILv3jdxgA/nZWrmmUxvXmOVDP1aNqN0jNhWGZQUruvfCdYg97e+eoRPtWxCrirND0SWPgsc7+JKHCt/I28goMYNwO3G9DNGAliNNKaJHfPZt0guFHCKmcKsIeenq45t7UdpYCaD7rvKuPHt2sLDRobXYrPyWBRkNP7wvOKwdjg9Kj4xV7Lho8HOoLQFT7LVBorl06I1fWZz/KHLBE0vxR149Mv7VWqiA45EoLQSkWpZxj/ICmCk3MwP3Zsh/37XYDY9ahR3D0M3dlRIcPE+6vL0DXHv7o9GZ8tJDtZ3wJu8lnVs2pYwpgiCdaX+VVk1mogpDI3fesFbleG9MRDv02Zk/IZuXg+pBNuoaAqTCLLtIdXscW1VnT9fMO2is/3SP0O8FPGfsCTXPO71gxKngyI0rFM09w3skqHXMrOzP2/+Eq730RrCFx8+I8ln+lAJ0jb8uw8LkWpm1/2xaiB+ZaKGcJMC8LyAZ4pXpc+Fob8FgDSfmqUwMzJx1GS7pchQdLB2E9nHalxeOQVA9tRlDlrOYJlc/6X7dJ6rr0jBNMuYZMr9GRoPalRV1xg24oLQ5n3McuR6Y+15dMO2lxFFRAQBojv2SMrtOOz3HnsFAFo2Yx43IilUmEgDfmgV96hsx1/k="

install:
  - source ./script/install_rustbook.sh
  - if [ $TRAVIS_PULL_REQUEST == "false" ] && [ $TRAVIS_BRANCH == "master" ]; then
      source ./script/install_calibre.sh;
    fi

before_script:
  - python --version
  - rustbook --version
  - if [ $TRAVIS_PULL_REQUEST == "false" ] && [ $TRAVIS_BRANCH == "master" ]; then
      ebook-convert --version;
    fi
  - ./script/fix.py
  - ./script/check.py

script:
  - ./script/build.sh

after_success:
  - if [ $TRAVIS_PULL_REQUEST == "false" ] && [ $TRAVIS_BRANCH == "master" ]; then
      ./script/convert.sh;
    fi
  - if [ $TRAVIS_PULL_REQUEST == "false" ] && [ $TRAVIS_BRANCH == "master" ]; then
      ./script/deploy.sh;
    fi

branches:
  only: master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9c2acdc270c9f1c84459
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

cache:
  directories:
    - $HOME/calibre

addons:
  apt:
    packages:
    - parallel

