language: rust
rust: nightly

sudo: true

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - cd additions/rustbook && cargo build --release
  - cp ./target/release/rustbook ./
  - cd ../../ && find . -maxdepth 1 -name '*.md' -exec sed -i 1s/#/%/ {} \;
  - ./additions/rustbook/rustbook build

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sudo -v && wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()" > /dev/null
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash additions/convert_book.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash additions/deploy.sh

branches:
  only: master

env:
  global:
    - secure: "OcQz/ppOUyKVZWlxlZYe0N9uzoWB2wR8WPMPxnliazIjQnpcwO9YE7phxIDppH2sLxgvGnGHHN356L73WAOYfWvKOiNa3kw3pvufSTI9wZqE087G9mgNe3XfnV9GFxGneaFdNm5vEe6LjRtDbr+CfJ/fhOBWI1dZkBZS9L8BIL7CCcs23uXEZCBN94/oF4P3z69y6Eah7Fx7KSLFiagWBsn6qnbQ9DCl9MATXWoYwlp5dpilevZ7IHELQ1edaFYdON9x/9vBthqRN2ohgATWzj4qxAe6nmgadN+CEsLYhFPWIapKrHc9KaRIelDFpUGP9XCVE7EIyGv2If4jd+nsMFgNUdwgcOxtXkvh5Ez5s0N0dXHKF/3R6m9ZwlwxhObnZ7HD+x/+UFLh/KqGbRBNK7o2bOHgHjpLhJJiEoeptlcsbtkzXsO09Q/Z5Zi/VwFjXR3uqeqg2QJd32YDEpvaDfKWSGN8/cm0Qqx8/tkE3JO5kGO68FH9tN0JQbw1b9Ci2Q9zu0KigzF3qyFTyzh+0t+8mSSF4l6wqDOZmq+t1RruZVKbOwK3OpxwMgGp0vYerKkcpeHVWXcoufN1zByJfMkm+UrI8eOzFjlX7vYBa93JvHR+IVUM8gMDnx9RgPc3qMX30bP76iGddsWI4ElamYc7ZcouDAujSn1Bi0dY7Z0="
